{{- if .Values.gatus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-gatus
  labels:
    app: gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: {{ .Values.gatus.image }}
          ports:
            - containerPort: {{ .Values.gatus.port }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-gatus
spec:
  selector:
    app: gatus
  ports:
    - protocol: TCP
      port: {{ .Values.gatus.port }}
      targetPort: {{ .Values.gatus.port }}
  type: ClusterIP
{{- end }}
