{{- if .Values.gatus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: {{ .Values.gatus.image }}
          ports:
            - containerPort: {{ .Values.gatus.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: gatus-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.gatus.port }}
  selector:
    app: gatus
{{- end }}